### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by jonschlinkert**

### CODE REVIEW

**Comment by paulmillr** [comment]
@jonschlinkert just a quick note. `to-regex` — which adds non-core functionality as far as I see — adds 0.3MB of deps. That's a lot.

```
to-regex  │ 21          │ 0.30M
```

**Comment by jonschlinkert** [comment]
> which adds non-core functionality as far as I see

Are you saying we should drop regex support from braces? How much of the 300k is safe-regex (the library that checks for catastrophic backtracking to prevent DDoS)? 

If this gets too complicated I'll have to plan time in the future to work on this.

**Comment by paulmillr** [comment]
@jonschlinkert here's `to-regex` (it says 0.13MB but in the end it's 0.3MB)

```
┌─────────────────┬────────────┬───────┐
│ name            │ children   │ size  │
├─────────────────┼────────────┼───────┤
│ define-property │ 7          │ 0.11M │
├─────────────────┼────────────┼───────┤
│ extend-shallow  │ 4          │ 0.04M │
├─────────────────┼────────────┼───────┤
│ regex-not       │ 2          │ 0.02M │
├─────────────────┼────────────┼───────┤
│ safe-regex      │ 1          │ 0.02M │
├─────────────────┼────────────┼───────┤
│ 4 modules       │ 9 children │ 0.13M │
└─────────────────┴────────────┴───────┘

```

**Comment by paulmillr** [comment]
@jonschlinkert as far as I see from the readme there's no support for `regex` api in the stable version of braces. So, in this case, i'd argue for keeping the api just as simple; and adding a readme notice on how to convert to `RegExp`s.

**Comment by paulmillr** [comment]
YAY! 🌈

Any ETA on the release?

**Comment by jonschlinkert** [comment]
> Any ETA on the release?

it's done. I just need to wrap it up and release. probably today

**Comment by paulmillr** [comment]
Great to see one less tool (appveyor).

**Comment by jonschlinkert** [comment]
@paulmillr FWIW I use a tool to generate documentation, the badges are in a template, so they'll automatically be updated. The appveyor badge is excluded if there is no `.appveyor.yml` file.

**Comment by paulmillr** [comment]
@jonschlinkert ping!

**Comment by jonschlinkert** [comment]
What are you pinging about @paulmillr?

**Comment by paulmillr** [comment]
Let's release it 😃

**Comment by jonschlinkert** [comment]
> Let's release it 😃

Are you volunteering to do the docs and changelog? :)

**Comment by paulmillr** [comment]
Working on `anymatch` & chokidar updates right now.

**Comment by paulmillr** [comment]
I’ve prepared new builds — Chokidar is 1/8th of previous size and feels super lean now. Can’t wait on getting these packages released!

**Comment by jonschlinkert** [comment]
> Can’t wait on getting these packages released!

I'll be working on it this weekend.

**Comment by jonschlinkert** [comment]
@paulmillr how's everything working out?

**Comment by paulmillr** [comment]
@jonschlinkert it’s awesome, we’re fixing tests across platforms and waiting for node 8.16

**Comment by jonschlinkert** [comment]
> we’re fixing tests across platforms and waiting for node 8.16

I hope I didn't break anything!

**Pull request merged**
